### ISSUE TITLE
Search list integration is success when lead is not found on list

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-marketo#1]
When a lead is not found on the specified list, the outcome should be a failure.

The API response looks like: 

```json
{
 "requestId": "e42b#14272d07d78",
 "result": [],
 "success": true
}
```

**Comment by alexkwolfe** [comment]
The same problem exists with the "get lead" integration.

**Comment by alexkwolfe** [comment]
There may be other integrations that have this same issue.

**Comment by cgrayson** [comment]
Looks to me like this can be closed now, and that the other two "get" integrations are ok.

1. `get_list` sets [failure on empty result](https://github.com/activeprospect/leadconduit-integration-marketo/blob/master/spec/get_list_spec.coffee#L67-L77)
2. `member_of_list` doesn't set outcome to failure, but it's [appending the boolean `is_member` value](https://github.com/activeprospect/leadconduit-integration-marketo/blob/master/spec/member_of_list_spec.coffee#L66-L75) rather than lead retrieval.
